### ISSUE TITLE
CsvParsingTest.xtend 

### ISSUE THREAD

**Issue by FAMILIAR-project** [manuelleduc/polymorphic-csv#2]
I can't make it working: 
https://github.com/manuelleduc/polymorphic-csv/blob/master/polymorphic.csv.tests/src/polymorphic/tests/CsvParsingTest.xtend

but I think it is deprecated. 
In general I would prefer we use some testing for playing with our pcsv files (instead of running a new Eclipse)

**Comment by manuelleduc** [comment]
Indeed it's deprecated, shame on me.
I'll update it soon and it's for sure a really good idea to maintains the test instead of starting and restarting modeling workbenches.

**Comment by manuelleduc** [comment]
Fixed by 7fe12f9dbd5986847624a4780c14acef7ec2ab13
